version: "3.8"

services:
  msedge:
    image: ${edge_image}
    container_name: edge
    restart: unless-stopped
    cpus: "${cpu_limit}"
    mem_limit: "${memory_limit}"
    shm_size: "2gb"
    ports:
      - "${server_port}:3001"
    volumes:
      - "/var/apps/edge/shares/data/config:/config"
      - "/var/apps/edge/shares/downloads:/downloads"
      - "./custom-cont-init.d:/custom-cont-init.d:ro"
    devices:
      - "/dev/dri:/dev/dri"
    environment:
      - PUID=${puid}
      - PGID=${pgid}
      - TZ=${timezone}
      - LC_ALL=${locale}
      - CUSTOM_USER=${edge_username}
      - PASSWORD=${edge_password}
      - SUBFOLDER=/edge/
      - EDGE_STARTUP_URL=${startup_url}
      - EDGE_WINDOW_SIZE=${edge_window_size}
      - EDGE_WINDOW_POSITION=${edge_window_position}
      - TITLE=${app_title}
      - PIXELFLUX_WAYLAND=${wayland_enabled}
      - DRINODE=${dri_render_node}
      - DRI_NODE=${dri_render_node}
      - MAX_RES=${max_res}
      - NO_DECOR=true
      - HARDEN_DESKTOP=true
      - HARDEN_OPENBOX=true
      - START_DOCKER=false
      - SELKIES_ENABLE_SHARING=false
      - SELKIES_ENABLE_COLLAB=false
      - SELKIES_ENABLE_SHARED=false
      - SELKIES_COMMAND_ENABLED=false
      - SELKIES_FILE_TRANSFERS=upload,download
      - FILE_MANAGER_PATH=/downloads
    security_opt:
      - no-new-privileges:true
    network_mode: bridge
