#!/bin/bash

FILE_PATH="${TRIM_APPDEST}/app/docker-compose.yaml"

is_docker_running() {
    for docker_name in edge; do
        echo "Checking Docker container: $docker_name"
        docker inspect "$docker_name" | grep -q "\"Status\": \"running\"," || exit 1
    done
}

case "$1" in
start)
    # Docker applications are started by App Center according to config/resource.
    exit 0
    ;;
stop)
    # Docker applications are stopped by App Center according to config/resource.
    exit 0
    ;;
status)
    if is_docker_running; then
        exit 0
    else
        exit 3
    fi
    ;;
*)
    exit 1
    ;;
esac
